### PR TITLE
Fix: Issue where the `command+k` shortcut cannot be triggered correctly on Mac. Adjusted the `meta` key detection logic to support Apple devices.

### LINKED ISSUE #177: Unable to Trigger command+k Hotkey on Mac
The command+k hotkey doesn't work on Mac, seems like a meta key detection issue.

### PR DESCRIPTION
**Pull request by sengoku-f**
### Fix #177 

- Fixed the issue where the `meta` key was not detected correctly on Mac, causing hotkeys to fail to trigger.

### CODE REVIEW

File: src/DocSearchModal.tsx [hunk 1]
```diff
@@ -317,6 +317,10 @@ export const DocSearchModal: Component<DocSearchModalProps> = ({
                             <a
                               href={hit.url || "#"}
                               aria-label={linkToTheResultAriaLabel}
+                              onClick={(e) => {
+                                // e.preventDefault();
+                                onClose && onClose();
+                              }}
```
Comment (amrbashir) [inline src/DocSearchModal.tsx]: why was this added?

**Review by amrbashir — APPROVED** [review]

**Comment by amrbashir** [comment]
Thank you

File: src/DocSearchModal.tsx (hunk 1 above)
Comment (sengoku-f) [reply src/DocSearchModal.tsx]: Because the search window will not close after the route jump in VitePress SPA

Comment (amrbashir) [reply src/DocSearchModal.tsx]: ah so it is related to #176 not #177, feel free to open another PR

Comment (amrbashir) [reply src/DocSearchModal.tsx]: Thank you for the fix, I've added it in https://github.com/tauri-apps/meilisearch-docsearch/commit/b03fb9484cd39fa5a684bf912ed4b05384ce0793 and attributed you.
